import { Property } from "../components/home-list/grid";

export const gridFake: Property[] = [
  {
    id: "1",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkKRD4k4PMWe4SJ6KlSVLLBphl0m9zlVjQ9M9eNORSqg&s=10",
    type: "Cabana",
    period: "3 – 4 de set.",
    location: "Florianópolis, SC",
    pricePerNight: 250,
    rating: 4.8,
  },
  {
    id: "2",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiGKmllrmIdOdXUfZAmIZqCGtHq0Y_3PpKqws2YbMp8g&s",
    type: "Loft",
    period: "3 – 4 de set.",
    location: "São Paulo, SP",
    pricePerNight: 180,
    rating: 4.5,
  },
  {
    id: "3",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSb0Z3nGpErd1a_Fkhjv2zQOIMCpDN17jgNNvULb-4onQ&s=10",
    type: "Casa",
    period: "3 – 4 de set.",
    location: "Gramado, RS",
    pricePerNight: 320,
    rating: 4.9,
  },
  {
    id: "4",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyQWnuxXpO7Vl1KzS8lCm7yRFCmFbTJ6ea5vQnWUTIEQ&s=10",
    type: "Cabana",
    period: "3 – 4 de set.",
    location: "Rio de Janeiro, RJ",
    pricePerNight: 210,
    rating: 4.6,
  },
  {
    id: "5",
    imageUrl: "https://picsum.photos/400/400?random=5",
    type: "Cabana",
    period: "5 – 7 de set.",
    location: "Canela, RS",
    pricePerNight: 275,
    rating: 4.92,
    reviewCount: 128,
    guests: 4,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    hostName: "Camping Paraíso Gramado",
    isSuperhost: true,
    description: "Seu refúgio de paz e sofisticação em Gramado te espera!\nDesfrute de cabanas com vista panorâmica para um bosque com córrego.",
    amenities: ["Wi-Fi", "Cozinha", "Estacionamento gratuito", "Permitido animais", "TV", "Ar-condicionado"],
  },
  {
    id: "6",
    imageUrl: "https://picsum.photos/400/400?random=6",
    type: "Apartamento",
    period: "10 – 12 de set.",
    location: "Curitiba, PR",
    pricePerNight: 165,
    rating: 4.7,
  },
  {
    id: "7",
    imageUrl: "https://picsum.photos/400/400?random=7",
    type: "Pousada",
    period: "1 – 3 de out.",
    location: "Búzios, RJ",
    pricePerNight: 340,
    rating: 4.85,
  },
  {
    id: "8",
    imageUrl: "https://picsum.photos/400/400?random=8",
    type: "Casa",
    period: "15 – 17 de set.",
    location: "Bonito, MS",
    pricePerNight: 290,
    rating: 4.95,
  },
  {
    id: "9",
    imageUrl: "https://picsum.photos/400/400?random=9",
    type: "Loft",
    period: "20 – 22 de set.",
    location: "Belo Horizonte, MG",
    pricePerNight: 150,
    rating: 4.6,
  },
  {
    id: "10",
    imageUrl: "https://picsum.photos/400/400?random=10",
    type: "Cabana",
    period: "8 – 10 de out.",
    location: "Campos do Jordão, SP",
    pricePerNight: 310,
    rating: 4.88,
  },
];