import { Property } from "../components/home-list/grid";

export const gridFake: Property[] = [
  {
    id: "1",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkKRD4k4PMWe4SJ6KlSVLLBphl0m9zlVjQ9M9eNORSqg&s=10",
    type: "Cabana",
    period: "3 – 4 de set.",
    location: "Florianópolis, SC",
    pricePerNight: 250,
    rating: 4.8,
    reviewCount: 96,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    hostName: "Renata Costa",
    isSuperhost: true,
    description: "Casa aconchegante a poucos minutos da praia, com vista para o mar e área externa completa.\nIdeal para famílias que buscam sossego sem abrir mão da praia pertinho.",
    amenities: ["Wi-Fi", "Cozinha", "Estacionamento gratuito", "Vista para o mar", "TV", "Ar-condicionado"],
  },
  {
    id: "2",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiGKmllrmIdOdXUfZAmIZqCGtHq0Y_3PpKqws2YbMp8g&s",
    type: "Loft",
    period: "3 – 4 de set.",
    location: "São Paulo, SP",
    pricePerNight: 180,
    rating: 4.5,
    reviewCount: 64,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    hostName: "Diego Almeida",
    isSuperhost: false,
    description: "Loft moderno no coração de São Paulo, a poucos passos de restaurantes e transporte público.\nPerfeito para quem viaja a trabalho ou quer explorar a cidade.",
    amenities: ["Wi-Fi", "Cozinha", "TV", "Ar-condicionado", "Elevador", "Academia no prédio"],
  },
  {
    id: "3",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSb0Z3nGpErd1a_Fkhjv2zQOIMCpDN17jgNNvULb-4onQ&s=10",
    type: "Casa",
    period: "3 – 4 de set.",
    location: "Gramado, RS",
    pricePerNight: 320,
    rating: 4.9,
    reviewCount: 152,
    guests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    hostName: "Família Weber",
    isSuperhost: true,
    description: "Casa espaçosa em meio à natureza de Gramado, com lareira e vista para as montanhas.\nÓtima opção para grupos e famílias grandes.",
    amenities: ["Wi-Fi", "Lareira", "Cozinha completa", "Estacionamento gratuito", "TV", "Permitido animais"],
  },
  {
    id: "4",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyQWnuxXpO7Vl1KzS8lCm7yRFCmFbTJ6ea5vQnWUTIEQ&s=10",
    type: "Cabana",
    period: "3 – 4 de set.",
    location: "Rio de Janeiro, RJ",
    pricePerNight: 210,
    rating: 4.6,
    reviewCount: 87,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    hostName: "Camila Santos",
    isSuperhost: false,
    description: "Cabana charmosa próxima ao Rio de Janeiro, cercada por natureza e tranquilidade.\nBoa opção para uma escapada de fim de semana perto da cidade.",
    amenities: ["Wi-Fi", "Cozinha", "Estacionamento gratuito", "TV", "Área externa"],
  },
  {
    id: "5",
    imageUrl: "https://picsum.photos/400/400?random=5",
    type: "Cabana",
    period: "5 – 7 de set.",
    location: "Canela, RS",
    pricePerNight: 275,
    rating: 4.92,
    reviewCount: 128,
    guests: 4,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    hostName: "Camping Paraíso Gramado",
    isSuperhost: true,
    description: "Seu refúgio de paz e sofisticação em Gramado te espera!\nDesfrute de cabanas com vista panorâmica para um bosque com córrego.",
    amenities: ["Wi-Fi", "Cozinha", "Estacionamento gratuito", "Permitido animais", "TV", "Ar-condicionado"],
  },
  {
    id: "6",
    imageUrl: "https://picsum.photos/400/400?random=6",
    type: "Apartamento",
    period: "10 – 12 de set.",
    location: "Curitiba, PR",
    pricePerNight: 165,
    rating: 4.7,
    reviewCount: 73,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    hostName: "Lucas Ferreira",
    isSuperhost: false,
    description: "Apartamento prático e bem localizado em Curitiba, ideal para viagens curtas.\nPróximo a mercados, cafés e pontos turísticos da cidade.",
    amenities: ["Wi-Fi", "Cozinha", "TV", "Elevador", "Ar-condicionado"],
  },
  {
    id: "7",
    imageUrl: "https://picsum.photos/400/400?random=7",
    type: "Pousada",
    period: "1 – 3 de out.",
    location: "Búzios, RJ",
    pricePerNight: 340,
    rating: 4.85,
    reviewCount: 201,
    guests: 5,
    bedrooms: 2,
    beds: 3,
    bathrooms: 2,
    hostName: "Pousada Vento Sul",
    isSuperhost: true,
    description: "Pousada aconchegante a poucos minutos das praias mais famosas de Búzios.\nCafé da manhã incluso e piscina compartilhada.",
    amenities: ["Wi-Fi", "Piscina", "Café da manhã incluso", "Estacionamento gratuito", "TV", "Ar-condicionado"],
  },
  {
    id: "8",
    imageUrl: "https://picsum.photos/400/400?random=8",
    type: "Casa",
    period: "15 – 17 de set.",
    location: "Bonito, MS",
    pricePerNight: 290,
    rating: 4.95,
    reviewCount: 168,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2,
    hostName: "Eco Bonito Hospedagens",
    isSuperhost: true,
    description: "Casa espaçosa perto dos principais passeios de Bonito, cercada por natureza exuberante.\nPerfeita para famílias e grupos de amigos.",
    amenities: ["Wi-Fi", "Cozinha completa", "Estacionamento gratuito", "Churrasqueira", "TV", "Ar-condicionado"],
  },
  {
    id: "9",
    imageUrl: "https://picsum.photos/400/400?random=9",
    type: "Loft",
    period: "20 – 22 de set.",
    location: "Belo Horizonte, MG",
    pricePerNight: 150,
    rating: 4.6,
    reviewCount: 59,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    hostName: "Bruna Oliveira",
    isSuperhost: false,
    description: "Loft compacto e moderno, próximo à região central de Belo Horizonte.\nÓtimo custo-benefício para viagens rápidas.",
    amenities: ["Wi-Fi", "Cozinha", "TV", "Ar-condicionado"],
  },
  {
    id: "10",
    imageUrl: "https://picsum.photos/400/400?random=10",
    type: "Cabana",
    period: "8 – 10 de out.",
    location: "Campos do Jordão, SP",
    pricePerNight: 310,
    rating: 4.88,
    reviewCount: 143,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    hostName: "Chalés Serra Fria",
    isSuperhost: true,
    description: "Cabana rústica com lareira, cercada pela paisagem de montanha de Campos do Jordão.\nPerfeita para curtir o friozinho com conforto.",
    amenities: ["Wi-Fi", "Lareira", "Cozinha", "Estacionamento gratuito", "TV", "Aquecedor"],
  },
];