USE airbnb;
CREATE TABLE properties (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
type VARCHAR(30) NOT NULL,
location VARCHAR(100) NOT NULL,
price_per_night DECIMAL(10,2) NOT NULL,
rating DECIMAL(3,2) DEFAULT 0 CHECK (rating >= 0 AND rating <= 5)
);
CREATE TABLE users (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(255),
  is_host BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  );
ALTER TABLE properties
ADD COLUMN host_id INT UNSIGNED NOT NULL,
ADD FOREIGN KEY (host_id) REFERENCES users(id);